// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProEventos.API.Data;

namespace MyProEventos.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MyProEventos.API.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventoData")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventoImagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventoLocal")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventoLote")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventoQtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventoTema")
                        .HasColumnType("TEXT");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
